### PR TITLE
fix: Use empty dict for schema of JSON/JSONB columns

### PR DESCRIPTION
**Pull request by edgarrmondragon**

### CODE REVIEW

**Comment by visch** [comment]
Hmm but you still want the target to know this is an object right? Are you saying all of the values here

```
id (int) data (jsonb)
-------- ------------
1        {"nested": "data"}
2        ["an", "array"]
3        3.14
```

Don't currently work? If so that's surprising to me!  

If they don't work the `type_dict` function should get updated.  Another solution that solves my problem and I think yours would be something like returning

```
{"type": "object"}
```
Which at least lets the target know that the data should be an object and can be put into the target system (database etc) as a `json` / `variant` object. 

By just returning `""` we're saying that the type can be anything not just an `object` which isn't true.

**Comment by edgarrmondragon** [comment]
> By just returning `""` we're saying that the type can be anything not just an `object` which isn't true.

I think it's actually true because [according to the spec](https://json-schema.org/understanding-json-schema/reference/object.html#object), `object` represents a map:

> Objects are the mapping type in JSON. They map “keys” to “values”. In JSON, the “keys” must always be strings. Each of these pairs is conventionally referred to as a “property”.

But a JSON/JSONB column can have not just objects, but also arrays, strings and numbers.

> Hmm but you still want the target to know this is an object right? Are you saying all of the values here

I'd want the target to know this can be any JSON stuff. The target should be able to handle that in a similar manner to https://github.com/MeltanoLabs/target-postgres/pull/183.

Wdyt @visch?

**Comment by visch** [comment]
> > By just returning `""` we're saying that the type can be anything not just an `object` which isn't true.
> 
> I think it's actually true because [according to the spec](https://json-schema.org/understanding-json-schema/reference/object.html#object), `object` represents a map:
> 
> > Objects are the mapping type in JSON. They map “keys” to “values”. In JSON, the “keys” must always be strings. Each of these pairs is conventionally referred to as a “property”.
> 
> But a JSON/JSONB column can have not just objects, but also arrays, strings and numbers.
> 
> > Hmm but you still want the target to know this is an object right? Are you saying all of the values here
> 
> I'd want the target to know this can be any JSON stuff. The target should be able to handle that in a similar manner to [MeltanoLabs/target-postgres#183](https://github.com/MeltanoLabs/target-postgres/pull/183).
> 
> Wdyt @visch?

Thanks for the lesson in JSON Schema :D I didn't realize that for objects. Implementation makes sense :D

**Comment by edgarrmondragon** [comment]
I think tests are failing due to https://github.com/meltano/sdk/issues/1969

**Comment by visch** [comment]
Tried testing this locally and hit an issue

```
create table test_jsonb(jsonbcol jsonb)
insert into test_jsonb (jsonbcol) values ('{}'), ('3.14'), ('["list","o","stuff"]')
```
```
Run invocation could not be completed as block failed: Cannot start plugin tap-postgres: Catalog discovery failed: command ['/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/bin/tap-postgres', '--config', '/home/visch/git/tap-postgres/.meltano/run/tap-postgres/tap.f516c931-fbcf-4a46-b66e-080fa5aa7c5c.config.json', '--discover'] returned 1 with stderr:
 Traceback (most recent call last):
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/bin/tap-postgres", line 8, in <module>
    sys.exit(TapPostgres.cli())
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 516, in cli
    tap = cls(  # type: ignore[operator]
  File "/home/visch/git/tap-postgres/tap_postgres/tap.py", line 37, in __init__
    super().__init__(*args, **kwargs)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 568, in __init__
    super().__init__(
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 103, in __init__
    self.mapper.register_raw_streams_from_catalog(self.catalog)
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 165, in catalog
    self._catalog = self.input_catalog or self._singer_catalog
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 286, in _singer_catalog
    for stream in self.streams.values()
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 128, in streams
    for stream in self.load_streams():
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 318, in load_streams
    for stream in self.discover_streams():
  File "/home/visch/git/tap-postgres/tap_postgres/tap.py", line 498, in discover_streams
    for catalog_entry in self.catalog_dict["streams"]
  File "/home/visch/git/tap-postgres/tap_postgres/tap.py", line 485, in catalog_dict
    result["streams"].extend(self.connector.discover_catalog_entries())
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/connectors/sql.py", line 494, in discover_catalog_entries
    catalog_entry = self.discover_catalog_entry(
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/connectors/sql.py", line 445, in discover_catalog_entry
    schema = table_schema.to_dict()
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/typing.py", line 254, in to_dict
    return self.type_dict  # type: ignore[no-any-return]
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/typing.py", line 704, in type_dict
    merged_props.update(w.to_dict())
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/typing.py", line 578, in to_dict
    type_dict = append_type(type_dict, "null")
  File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/helpers/_typing.py", line 59, in append_type
    raise ValueError(
ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
```

**Review by visch — CHANGES_REQUESTED** [review]
Comment on PR

**Comment by visch** [comment]
> Tried testing this locally and hit an issue
> 
> ```
> create table test_jsonb(jsonbcol jsonb)
> insert into test_jsonb (jsonbcol) values ('{}'), ('3.14'), ('["list","o","stuff"]')
> ```
> 
> ```
> Run invocation could not be completed as block failed: Cannot start plugin tap-postgres: Catalog discovery failed: command ['/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/bin/tap-postgres', '--config', '/home/visch/git/tap-postgres/.meltano/run/tap-postgres/tap.f516c931-fbcf-4a46-b66e-080fa5aa7c5c.config.json', '--discover'] returned 1 with stderr:
>  Traceback (most recent call last):
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/bin/tap-postgres", line 8, in <module>
>     sys.exit(TapPostgres.cli())
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 516, in cli
>     tap = cls(  # type: ignore[operator]
>   File "/home/visch/git/tap-postgres/tap_postgres/tap.py", line 37, in __init__
>     super().__init__(*args, **kwargs)
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 568, in __init__
>     super().__init__(
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 103, in __init__
>     self.mapper.register_raw_streams_from_catalog(self.catalog)
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 165, in catalog
>     self._catalog = self.input_catalog or self._singer_catalog
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 286, in _singer_catalog
>     for stream in self.streams.values()
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 128, in streams
>     for stream in self.load_streams():
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 318, in load_streams
>     for stream in self.discover_streams():
>   File "/home/visch/git/tap-postgres/tap_postgres/tap.py", line 498, in discover_streams
>     for catalog_entry in self.catalog_dict["streams"]
>   File "/home/visch/git/tap-postgres/tap_postgres/tap.py", line 485, in catalog_dict
>     result["streams"].extend(self.connector.discover_catalog_entries())
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/connectors/sql.py", line 494, in discover_catalog_entries
>     catalog_entry = self.discover_catalog_entry(
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/connectors/sql.py", line 445, in discover_catalog_entry
>     schema = table_schema.to_dict()
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/typing.py", line 254, in to_dict
>     return self.type_dict  # type: ignore[no-any-return]
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/typing.py", line 704, in type_dict
>     merged_props.update(w.to_dict())
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/typing.py", line 578, in to_dict
>     type_dict = append_type(type_dict, "null")
>   File "/home/visch/git/tap-postgres/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/singer_sdk/helpers/_typing.py", line 59, in append_type
>     raise ValueError(
> ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
> ```

I'm confused though as my local `pytest` fails with the same error on multiple tests 

```
FAILED tests/test_core.py::test_temporal_datatypes - ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
FAILED tests/test_core.py::test_jsonb_json - ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
FAILED tests/test_core.py::test_decimal - ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
FAILED tests/test_core.py::test_invalid_python_dates - ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
FAILED tests/test_replication_key.py::test_null_replication_key_with_start_date - ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
FAILED tests/test_replication_key.py::test_null_replication_key_without_start_date - ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
FAILED tests/test_ssl.py::test_ssl - ValueError: Could not append type because the JSON schema for the dictionary `{}` appears to be invalid.
```

Trying to understand this maybe it's a local setup thing hmm

**Comment by edgarrmondragon** [comment]
> > Tried testing this locally and hit an issue

@visch You might need to do `poetry install`

**Comment by visch** [comment]
Since the tests pass this seems good, merging

**Review by visch — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
@Lawiss Thanks for trying it out. I think we need a guard upstream to end early if the property schema is empty: https://github.com/meltano/sdk/blob/039c06f8b6c07a3cb33028759ca65e806226a6ad/singer_sdk/helpers/_typing.py#L424. I might get to it at some point this week, but feel free to send us a PR is you wish.

Another option is to revert this PR and think of a better approach.

**Pull request merged**
