### PR TITLE
packaging: Add faker extra dependency to singer-sdk

### PR DESCRIPTION
**Pull request by maxmarcon**
Fixes: #493

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
@maxmarcon I can't push to your `main` branch, can you run `poetry lock` and push the changes to `poetry.lock`? Thanks!

**Comment by maxmarcon** [comment]
@edgarrmondragon I did it and pushed the changes. Thanks

**Review by edgarrmondragon — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
thanks @maxmarcon!

**Comment by maxmarcon** [comment]
You're welcome @edgarrmondragon ! Thanks for creating a new release

**Pull request merged**
