### PR TITLE
fix: Error with JSONB columns containing arrays.

### PR DESCRIPTION
**Pull request by sebastianswms**
Postgres JSONB columns would always be reported as jsonschema objects, even though they can sometimes hold jsonschema arrays. This can cause downstream issues, such as those documented in the below target-postgres issue.

Closes https://github.com/MeltanoLabs/target-postgres/issues/189

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
@sebastianswms @visch I'm curious what you think of the more general solution in #239?

**Comment by visch** [comment]
@edgarrmondragon #239 seems better

I dislike how counter-intuitive it is from a user's perspective as If I"m pulling a JSONB column I'd assume it's going to serialize as an object in jsonschema. So we should probably add a decent readme with the examples. @edgarrmondragon  has examples in that issue would help folks understand the why here (JSONB can have a bunch of values) 

What do you think @sebastianswms  curious if you have a different opinion. If not we should just get edgars PR in. It looks like I tested it and just needed to upgrade my dependencies (I was testing the different scenario's myself)

**Comment by sebastianswms** [comment]
This goes deeper than I thought. After reading through #239 it seems like a fully variant schema is the better solution.

**Comment by visch** [comment]
We should close this one based on https://github.com/MeltanoLabs/tap-postgres/pull/279#issuecomment-1779791625 right @sebastianswms  ?

**Comment by sebastianswms** [comment]
Closed because #239 is better.

**Pull request closed without merging**
